// <auto-generated />
using LegendWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LegendWeb.Migrations
{
    [DbContext(typeof(LegendDbContext))]
    [Migration("20220105101411_month")]
    partial class month
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("LegendWeb.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = "c52f3d44-c922-4506-8f54-410efa1113ce",
                            City = "Lagos",
                            Country = "Nigeria",
                            Street = "2013, Adunni Oluwole Loop, Fara park 2 Estate, Lekki-Epe Expressway",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("LegendWeb.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("LegendWeb.Models.Information", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageThumbNailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkStatus")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Age = "23",
                            Bio = "With experience in developing scalable applications, I am highly proficient and committed to building innovative software applications. I’m in tune with the latest technological trends and I use them to build efficient software applications.",
                            DateOfBirth = "17th of September",
                            Degree = "Proficient",
                            Description = "I am a Software Engineer from Lagos",
                            Education = "B.Sc (Hons) Biochemistry, Obafemi Awolowo University",
                            Email = "fadeniayobami@gmail.com",
                            FirstName = "Ayobami",
                            Gender = "Male",
                            ImageThumbNailUrl = "images/2.jpg",
                            ImageUrl = "images/1.jpg",
                            JobTitle = "Fullstack Software Engineer",
                            LastName = "Fadeni",
                            PhoneNumber = "+234-8106322363",
                            WorkStatus = "Available"
                        });
                });

            modelBuilder.Entity("LegendWeb.Models.Projects", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = "027dd8c2-2d3a-451b-8010-83b4540474ab",
                            Body = "An online marketplace for livestocks integrated with  payment gateway",
                            ImageUrl = "images/work4.png",
                            Name = "Livestock247 Web App",
                            Url = "http://livestockfarms.herokuapp.com/",
                            UserId = "1"
                        },
                        new
                        {
                            Id = "2d5800b4-231a-4e17-8f3a-29d08de7333c",
                            Body = "PlentyTechJobs is the one platform for finding the best technology jobs",
                            ImageUrl = "images/PTJ.png",
                            Name = "PlentyTechJobs",
                            Url = "https://plentytechjobs.africa",
                            UserId = "1"
                        },
                        new
                        {
                            Id = "94658f38-1310-4264-b6ba-880d0f9f316b",
                            Body = "Omney is an application that will let users buy and sell stocks",
                            ImageUrl = "images/Omney.png",
                            Name = "Omney",
                            Url = "http://legendary-ay.herokuapp.com/",
                            UserId = "1"
                        },
                        new
                        {
                            Id = "ff7a41ec-40bc-4e81-b58c-0d9b76e44b53",
                            Body = "A Javascript application that creates random passwords",
                            ImageUrl = "images/work1.png",
                            Name = "Password Generator",
                            Url = "https://legendaryay.github.io/PasswordGenerator/",
                            UserId = "1"
                        },
                        new
                        {
                            Id = "8fea0763-7325-40cb-9a2d-46fff0e33a67",
                            Body = "A RESTful API for managing contacts",
                            ImageUrl = "images/work5.png",
                            Name = "ContactMangerAPI",
                            Url = "https://github.com/LegendaryAy/ContactManagerApi",
                            UserId = "1"
                        },
                        new
                        {
                            Id = "5e859116-1d1c-4917-8b3e-ac3c1aa60abe",
                            Body = "A simple Bank application that performs basic transactions",
                            ImageUrl = "images/work6.png",
                            Name = "LegendBank",
                            Url = "https://github.com/LegendaryAy/LegendBank",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("LegendWeb.Models.Skills", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = "e97aa8be-5b87-41bb-9355-f2efdb24be6f",
                            Name = "HTML",
                            Progress = 100,
                            UserId = "1"
                        },
                        new
                        {
                            Id = "76c348dd-fc61-4984-b967-a21f55db0c27",
                            Name = "CSS",
                            Progress = 95,
                            UserId = "1"
                        },
                        new
                        {
                            Id = "18f6fcfb-82e2-4cd5-b9b3-5c47f64b4487",
                            Name = "JavaScript",
                            Progress = 89,
                            UserId = "1"
                        },
                        new
                        {
                            Id = "dee9bf4c-db2a-440a-bdab-d9da29424ff1",
                            Name = "C#",
                            Progress = 90,
                            UserId = "1"
                        },
                        new
                        {
                            Id = "4097e361-7391-4d40-8152-a9616332e3da",
                            Name = "SQL",
                            Progress = 82,
                            UserId = "1"
                        },
                        new
                        {
                            Id = "df3c3ed9-f4d8-4cfd-843c-b99eca5b9450",
                            Name = "PHP",
                            Progress = 86,
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("LegendWeb.Models.Address", b =>
                {
                    b.HasOne("LegendWeb.Models.Information", "User")
                        .WithOne("Address")
                        .HasForeignKey("LegendWeb.Models.Address", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegendWeb.Models.Projects", b =>
                {
                    b.HasOne("LegendWeb.Models.Information", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegendWeb.Models.Skills", b =>
                {
                    b.HasOne("LegendWeb.Models.Information", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegendWeb.Models.Information", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Projects");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
